[[main]]
  identifier = "docs"
  name = "Docs"
  url = "docs"
  weight = 1

[[main]]
  identifier = "libs"
  name = "Libs"
  url = "libs"
  weight = 2

[[main]]
  identifier = "blog"
  name = "Blog"
  url = "blog"
  weight = 3

[[main]]
  identifier = "hub"
  name = "Hub"
  url = "hub"
  weight = 4





# Doc versions params
# Create a separate [[versions]] set for every version / doc set branch
# Use the ghbranchname param for specifying the GitHub branchname ->
# Example:
#   [thisisalink](https://github.com/.../tree/{{< params "ghbranchname" >}}/...)
#
# [[versions]] - Defines a single "version" of the docs
#   version - Intuitive version label (ie. visible in menus)
#   ghbranchname - Name of branch of the doc version in GitHub
#                  (https://github.com/<username>/docs/branches)
#   url - Fully qualified website URL to the doc version
#         (ie. https://www.<domain>.dev/[dirpath])
#   dirpath - The content folder name of the doc version
#           - Latest release is always set to "docs"
#           - Past/archived releases change to "v#.#-docs",
#             where # is the MAJOR and MINOR semantic version values

# Latest version
################
# Set to "docs" path

[[versions]]
  version = "v0.12"
  ghbranchname = "release-0.12"
  url = "/docs/"
  dirpath = "docs"

# Archived versions
###################
# Prefix all past versions with release # "v#.#-docs"

[[versions]]
  version = "v0.11"
  ghbranchname = "release-0.11"
  url = "/v0.11-docs/"
  dirpath = "v0.11-docs"

[[versions]]
  version = "v0.10"
  ghbranchname = "release-0.10"
  url = "/v0.10-docs/"
  dirpath = "v0.10-docs"

[[versions]]
  version = "v0.9"
  ghbranchname = "release-0.9"
  url = "/v0.9-docs/"
  dirpath = "v0.9-docs"

[[versions]]
  version = "Archives"
  ghbranchname = ""
  url = "https://github.com/zzossig/hugo-theme-zdoc/branches"
  dirpath = ""

# Pre-release version
###################
# In-development (pre-release) content - "master" branch

[[versions]]
  version = "Pre-release"
  ghbranchname = "master"
  url = "/development/"
  dirpath = "development"
