[[main]]
  identifier = "docs"
  name = "Docs"
  url = "docs"
  weight = 1

[[main]]
  identifier = "libs"
  name = "Libs"
  url = "libs"
  weight = 2

[[main]]
  identifier = "blog"
  name = "Blog"
  url = "blog"
  weight = 3

[[main]]
  identifier = "hub"
  name = "Hub"
  url = "hub"
  weight = 4
