logo = true
logoText = "FOL"
logoType = "short" # long, short
description = "Follang"
themeOptions = ["dark", "light"]
useFaviconGenerator = true # https://www.favicon-generator.org/
enableTocSwitch = true
enableLandingBackground = false
enableSearch = true
enableSearchHighlight = true
enableLangChange = true
enableDarkMode = true
enableBreadcrumb = true
enableBlogBreadcrumb = true
enableEditBtn = false
enableToc = true
enableMenu = true
enableNavbar = true
enableFooter = true
showPoweredBy = false

tocLevels = ["h1", "h2", "h3", "h4"]
paginateWindow = 1
taxoPaginate = 13
taxoGroupByDate = "2006" # "2006-01": group by month, "2006": group by year

github = "https://github.com/follang/fol"

# comment
enableComment = true
disqus_shortname = ""
commento = false


# FOL DEFAULT Site Params
########################
# Default docs parameters

# GitHub branch (latest release)
latest_github_branch = "master"
# Default version (latest release)
version = "v0.12"
########################

# Section labels for versions
# Current release
doclabel = "Documentation "
releaselabel = "Release: "
# Pre-release
masterlabel = "Pre-release"
# section path value ("master" docs directory folder on website)
masterfolder = "docs"

# Footer content
folAuthors = "FOL"
folLicense = "FOL Licensing"
fol_license = "https://github.com/follang/fol/blob/master/LICENSE.md"

# GitHub repositories
github_docsrepo = "https://github.com/follang/docs"
github_communityrepo = "https://github.com/follang/community"
github_eventingrepo = "https://github.com/follang/eventing"
github_servingrepo = "https://github.com/follang/serving"



# Doc versions params
# Create a separate [[versions]] set for every version / doc set branch
# Use the ghbranchname param for specifying the GitHub branchname ->
# Example:
#   [thisisalink](https://github.com/.../tree/{{< params "ghbranchname" >}}/...)
#
# [[versions]] - Defines a single "version" of the docs
#   version - Intuitive version label (ie. visible in menus)
#   ghbranchname - Name of branch of the doc version in GitHub
#                  (https://github.com/<username>/docs/branches)
#   url - Fully qualified website URL to the doc version
#         (ie. https://www.<domain>.dev/[dirpath])
#   dirpath - The content folder name of the doc version
#           - Latest release is always set to "docs"
#           - Past/archived releases change to "v#.#-docs",
#             where # is the MAJOR and MINOR semantic version values

# Latest version
################
# Set to "docs" path

[[versions]]
  version = "v0.12"
  ghbranchname = "master"
  url = "/docs/"
  dirpath = "docs"

# Archived versions
###################
# Prefix all past versions with release # "v#.#-docs"

[[versions]]
  version = "v0.11"
  ghbranchname = "release-0.11"
  url = "/v0.11-docs/"
  dirpath = "v0.11-docs"

[[versions]]
  version = "v0.10"
  ghbranchname = "release-0.10"
  url = "/v0.10-docs/"
  dirpath = "v0.10-docs"

[[versions]]
  version = "v0.9"
  ghbranchname = "release-0.9"
  url = "/v0.9-docs/"
  dirpath = "v0.9-docs"

[[versions]]
  version = "Archives"
  ghbranchname = ""
  url = "https://github.com/zzossig/hugo-theme-zdoc/branches"
  dirpath = ""

# Pre-release version
###################
# In-development (pre-release) content - "master" branch

[[versions]]
  version = "Pre-release"
  ghbranchname = "master"
  url = "/development/"
  dirpath = "development"
